import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import dynamic from 'next/dynamic';

interface Props {
  data: MapData[];
}

const Home: NextPage<Props> = ({ data }) => {
  const MapNoSSR = dynamic(() => import('modules/map/MapNoSSR'), {
    ssr: false,
  });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MapNoSSR mapData={data} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch('https://dinomapping.herokuapp.com/maps/all/');
  const data: MapData[] = await response.json();

  return { props: { data } };
};

export default Home;
